spring.application.name=joppe
server.port=8888

# Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/joppe_db
spring.datasource.username=joppe_system_account
spring.datasource.password=joppe_system_account
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Security
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000

# Google OAuth
application.security.google.client-id=550528781906-h18cpo4fdom7ebbj72utgj5hffnr0dnt.apps.googleusercontent.com
